# netlify.toml
[build]
  # publish is the folder with your index.html, styles.css, etc.
  publish = "."
  # command is blank because this is a plain static site
  command = ""

# ---------- Security & Headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# ---------- Caching ----------
# Cache images aggressively; let Netlify build pipeline bust cache on deploy
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------- Netlify Image Transform defaults ----------
[images]
  # ensures WebP/AVIF generation if a browser supports it
  format = ["webp", "avif"]

# ---------- Environment contexts (optional examples) ----------
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"