[[headers]]
for = "/*"
[headers.values]
access-control-allow-origin = "https://wow.mel.quest"

[[redirects]]
  from = "/*"
  to = "https://wowbuilds.nightsidecode.com/:splat"
  status = 301
  force = true
  conditions = { Host = [wow.mel.quest"] }